Xnb lattice collection
Collab4exaNBody/exaNBody pull request #76
Opened 2024-11-15 11:15 UTC by lafourcadep

Added custom lattice definition and cleaned all lattice generator to avoid code duplication. 
The different lattice operator are the following : 
lattice_generator.cpp                  -> baseline operator
legacy_lattice_generator.cpp     -> similar but with internal init_rcb_grid (Additional boolean)
bulk_lattice_generator.cpp         -> similar but this one initializes the domain on its own and is dedicated to 3D periodic boundary conditions! specific to MD where the entire domain is filled with a specific lattice that needs to be perfectly commensurated with the domain.

Two other PRs will be opened for exaStamp and exaDEM to which I added examples for test purposes.

2024-11-20 18:41 UTC, rprat-pro requested changes
@lafourcadep @carrardt I confirm that it works with exaDEM =)

2024-11-20 18:41 UTC, rprat-pro commented on src/exanb/grid_cell_particles/include/exanb/grid_cell_particles/lattice_generator.h
> +          double px = (*positions)[i].x;
Add `[[maybe_unused]]` here for compiler or define this section `#ifndef NDEGUB` (avoid warning)

px, py, pz

2024-11-20 18:41 UTC, rprat-pro commented on src/exanb/grid_cell_particles/include/exanb/grid_cell_particles/lattice_generator.h
> +        for (int i=0;i<(*positions).size();i++) {
size_t i instead of i

2024-11-25 09:55 UTC, carrardt approved these changes
Everything's fine, thank's for the work

2024-11-25 10:04 UTC, merged